### ISSUE TITLE
Resource Packs Support

### ISSUE THREAD

**Issue by SuperXingKong** [GenisysPro/GenisysPro#7]
# TODO:
- [x] ResourcePackManger and network packs
- [x] Send it to  players
- [ ] More features and bug fix

**Comment by SuperXingKong** [comment]
Well, who can test it and report to me?

**Comment by MCNationPE** [comment]
i will test it

**Comment by MCNationPE** [comment]
[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\resourcepacks\ZippedResourcePack::getVersion()" (EXCEPTION) in "/src/pocketmine/network/protocol/ResourcePacksInfoPacket" at line 55

**Comment by SuperXingKong** [comment]
@MCNationPE Fixed , thank you for your report !

**Comment by SuperXingKong** [comment]
Maybe it works well ?

**Comment by MCNationPE** [comment]
![image](https://cloud.githubusercontent.com/assets/28045745/25778357/aa70ce66-3325-11e7-85fa-13a05eae7e43.png)

**Comment by mote166** [comment]
has anyone tested this yet? if so does it work properly? and how can we use it?

**Comment by SuperXingKong** [comment]
@mote166 Make sure you have already installed OpenSSL and zip extensions.Then read your-server-dir/resource_packs/resource_packs.yml
